<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="IBM-PG02TZZN" failures="15" tests="16" name="Create a customer" time="8.499" errors="0" timestamp="02 Oct 2023 09:08:13 GMT">
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationValidKey" time="2.133">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPIbasic.cxCreationValidKey(CreateCustomerStripeAPIbasic.java:24)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationValidKey" time="0.505">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPIbasic.cxCreationValidKey(CreateCustomerStripeAPIbasic.java:24)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationValidKey" time="0.976">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationValidKey(CreateCustomerStripeAPI2.java:21)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationValidKey" time="0.976">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationValidKey(CreateCustomerStripeAPI2.java:21)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationValidKey" time="1.008">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationValidKey(CreateCustomerStripeAPI2.java:21)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationValidKey" time="0.519">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationValidKey(CreateCustomerStripeAPI.java:20)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationValidKey" time="0.519">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationValidKey(CreateCustomerStripeAPI.java:20)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationValidKey" time="1.132">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationValidKey(CreateCustomerStripeAPI.java:20)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationInvalidKey" time="0.51">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPIbasic.cxCreationInvalidKey(CreateCustomerStripeAPIbasic.java:33)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationInvalidKey" time="1.014">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPIbasic.cxCreationInvalidKey(CreateCustomerStripeAPIbasic.java:33)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationInvalidKey" time="0.619">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationInvalidKey(CreateCustomerStripeAPI2.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationInvalidKey" time="1.051">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationInvalidKey(CreateCustomerStripeAPI2.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationInvalidKey" time="1.073">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationInvalidKey(CreateCustomerStripeAPI2.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationInvalidKey" time="0.797">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationInvalidKey(CreateCustomerStripeAPI.java:30)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationInvalidKey" time="0.796">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationInvalidKey(CreateCustomerStripeAPI.java:30)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationInvalidKey" time="1.077">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationInvalidKey(CreateCustomerStripeAPI.java:30)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="baseClass.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
  <testcase classname="baseClass.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
</testsuite> <!-- Create a customer -->
