<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="IBM-PG02TZZN" failures="16" tests="16" name="Create a customer" time="8.104" errors="0" timestamp="17 Sep 2023 10:35:40 GMT">
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationValidKey" time="1.811">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPIbasic.cxCreationValidKey(CreateCustomerStripeAPIbasic.java:24)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationValidKey" time="1.161">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPIbasic.cxCreationValidKey(CreateCustomerStripeAPIbasic.java:24)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationValidKey" time="0.689">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationValidKey(CreateCustomerStripeAPI2.java:21)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationValidKey" time="0.725">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationValidKey(CreateCustomerStripeAPI2.java:21)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationValidKey" time="1.019">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationValidKey(CreateCustomerStripeAPI2.java:21)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationValidKey" time="0.612">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationValidKey(CreateCustomerStripeAPI.java:20)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationValidKey" time="0.615">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationValidKey(CreateCustomerStripeAPI.java:20)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationValidKey" time="0.633">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationValidKey(CreateCustomerStripeAPI.java:20)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationValidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationInvalidKey" time="0.689">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPIbasic.cxCreationInvalidKey(CreateCustomerStripeAPIbasic.java:33)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationInvalidKey" time="0.613">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPIbasic.cxCreationInvalidKey(CreateCustomerStripeAPIbasic.java:33)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationInvalidKey" time="0.519">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationInvalidKey(CreateCustomerStripeAPI2.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationInvalidKey" time="0.599">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationInvalidKey(CreateCustomerStripeAPI2.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationInvalidKey" time="0.693">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI2.cxCreationInvalidKey(CreateCustomerStripeAPI2.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationInvalidKey" time="0.672">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationInvalidKey(CreateCustomerStripeAPI.java:30)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationInvalidKey" time="0.746">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationInvalidKey(CreateCustomerStripeAPI.java:30)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationInvalidKey" time="1.414">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at testCases.CreateCustomerStripeAPI.cxCreationInvalidKey(CreateCustomerStripeAPI.java:30)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cxCreationInvalidKey -->
  <testcase classname="baseClass.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
  <testcase classname="baseClass.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
</testsuite> <!-- Create a customer -->
